interface SchoolBuilding {
	Code: string;
	Building: string;
	Location: string;
}

// export const schoolBuildings: SchoolBuilding[] = [
// 	{ Code: 'APM', Building: 'Applied Physics and Mathematics Building', Location: 'Muir' },
// 	{ Code: 'ARTH', Building: 'Arthur Wagner Theatre', Location: 'Revelle' },
// 	{ Code: 'ASANT', Building: 'Asante Hall', Location: 'Eleanor Roosevelt' },
// 	{ Code: 'BIO', Building: 'Muir Biology Building', Location: 'Muir' },
// 	{ Code: 'BIRCH', Building: 'Birch Aquarium', Location: 'SIO' },
// 	{ Code: 'BONN', Building: 'Bonner Hall', Location: 'Revelle' },
// 	{ Code: 'BSB', Building: 'Biomedical Sciences Building', Location: 'Medical School' },
// 	// { Code: 'CCC', Building: 'Cross-Cultural Center', Location: 'University Center' },
// 	{ Code: 'CENTR', Building: 'Center Hall', Location: 'University Center' },
// 	{
// 		Code: 'CICC',
// 		Building: 'Copely International Conference Center',
// 		Location: 'Eleanor Roosevelt',
// 	},
// 	{
// 		Code: 'CILAS',
// 		Building: 'Latin American Studies',
// 		Location: 'Eleanor Roosevelt',
// 	},
// 	// { Code: 'CLIN', Building: 'Clinical Sciences Building', Location: 'Medical School' },
// 	// { Code: 'CMG', Building: 'Center for Molecular Genetics', Location: 'Medical School' },
// 	// { Code: 'CMME', Building: 'Center for Molecular Medicine East', Location: 'Medical School' },
// 	{ Code: 'CMMW', Building: 'Palade Labs', Location: 'Medical School' },
// 	{ Code: 'CMRR', Building: 'Center for Magnetic Recording Research', Location: 'Warren' },
// 	{
// 		Code: 'CNCB',
// 		Building: 'Center for Neural Circuits and Behavior',
// 		Location: 'Medical School',
// 	},
// 	{ Code: 'CPMC', Building: 'Conrad Prebys Music Center', Location: 'University Center' },
// 	{ Code: 'CRB', Building: 'Chemistry Research Building', Location: 'Thurgood Marshall' },
// 	{ Code: 'CSB', Building: 'Cognitive Science Building', Location: 'Thurgood Marshall' },
// 	{ Code: 'DANCE', Building: 'Wagner Dance Building', Location: 'Revelle' },
// 	{ Code: 'DSD', Building: 'Deep Sea Drilling Building', Location: 'SIO' },
// 	{ Code: 'EBU1', Building: 'Engineering Building Unit 1', Location: 'Warren' },
// 	{ Code: 'EBU2', Building: 'Engineering Building Unit 2', Location: 'Warren' },
// 	{ Code: 'EBU3B', Building: 'Computer Science and Engineering Building', Location: 'Warren' },
// 	{ Code: 'ECKRT', Building: 'Eckart Building', Location: 'SIO' },
// 	{ Code: 'ECON', Building: 'Economics Building', Location: 'Thurgood Marshall' },
// 	{
// 		Code: 'ERCA',
// 		Building: 'Eleanor Roosevelt College Administration',
// 		Location: 'Eleanor Roosevelt',
// 	},
// 	{ Code: 'FORUM', Building: 'Mandell Weiss Forum', Location: 'Revelle' },
// 	{ Code: 'GEISL', Building: 'Geisel Library', Location: 'University Center' },
// 	{ Code: 'GH', Building: 'Galbraith Hall', Location: 'Revelle' },
// 	{
// 		Code: 'HSS',
// 		Building: 'Humanities & Social Sciences Building',
// 		Location: 'Muir',
// 	},
// 	{
// 		Code: 'HUBBS',
// 		Building: 'Hubbs Hall',
// 		Location: 'SIO',
// 	},
// 	{
// 		Code: 'IGPP',
// 		Building: 'Institute of Geophysics & Planetary Physics - Munk Lab',
// 		Location: 'SIO',
// 	},
// 	{
// 		Code: 'IGPP',
// 		Building: 'Institute of Geophysics & Planetary Physics - Revelle Lab',
// 		Location: 'SIO',
// 	},
// 	{
// 		Code: 'IOA',
// 		Building: 'Institute of the Americas',
// 		Location: 'Eleanor Roosevelt',
// 	},
// 	{
// 		Code: 'LASB',
// 		Building: 'Gildred Latin American Studies Building',
// 		Location: 'Eleanor Roosevelt',
// 	},
// 	{
// 		Code: 'LEDDN',
// 		Building: 'Patrick J. Ledden Auditorium (formerly HSS 2250)',
// 		Location: 'Muir',
// 	},
// 	{
// 		Code: 'LFFB',
// 		Building: 'Leichtag Family Foundation Biomedical Research Building',
// 		Location: 'Medical School',
// 	},
// 	{
// 		Code: 'LIT',
// 		Building: 'Literature Building',
// 		Location: 'Warren',
// 	},
// 	{
// 		Code: 'MANDE',
// 		Building: 'Mandeville Center',
// 		Location: 'Muir',
// 	},
// 	{
// 		Code: 'MAYER',
// 		Building: 'Mayer Hall',
// 		Location: 'Revelle',
// 	},
// 	{
// 		Code: 'MYR-A',
// 		Building: 'Mayer Hall Addition',
// 		Location: 'Revelle',
// 	},
// 	{
// 		Code: 'MCC',
// 		Building: 'Media Center/Communication Building',
// 		Location: 'Thurgood Marshall',
// 	},
// 	{
// 		Code: 'MCGIL',
// 		Building: 'McGill Hall',
// 		Location: 'Muir',
// 	},
// 	{
// 		Code: 'MNDLR',
// 		Building: 'Mandler Hall (formerly McGill Hall Annex)',
// 		Location: 'Muir',
// 	},
// 	{
// 		Code: 'MTF',
// 		Building: 'Medical Teaching Facility',
// 		Location: 'Medical School',
// 	},
// 	{
// 		Code: 'MWEIS',
// 		Building: 'Mandell Weiss Theatre',
// 		Location: 'Revelle',
// 	},
// 	{
// 		Code: 'NIERN',
// 		Building: 'Nierenberg Hall',
// 		Location: 'SIO',
// 	},
// 	{
// 		Code: 'NSB',
// 		Building: 'Natural Sciences Building',
// 		Location: 'Revelle',
// 	},
// 	{
// 		Code: 'NTV',
// 		Building: 'Nierenberg Hall Annex',
// 		Location: 'SIO',
// 	},
// 	{
// 		Code: 'OAR',
// 		Building: 'Keck Center for Ocean & Atmospheric Research',
// 		Location: 'SIO',
// 	},
// 	{
// 		Code: 'OFF',
// 		Building: 'Off Campus',
// 		Location: 'Off Campus',
// 	},
// 	{
// 		Code: 'OTRSN',
// 		Building: 'Otterson Hall (Main building for Rady)',
// 		Location: 'Rady',
// 	},
// 	{
// 		Code: 'PACIF',
// 		Building: 'Pacific Hall',
// 		Location: 'Revelle',
// 	},
// 	{
// 		Code: 'PC',
// 		Building: 'Price Center',
// 		Location: 'University Center',
// 	},
// 	{
// 		Code: 'PCYNH',
// 		Building: 'Pepper Canyon Hall',
// 		Location: 'University Center',
// 	},
// 	{
// 		Code: 'PETER',
// 		Building: 'Peterson Hall',
// 		Location: 'Thurgood Marshall',
// 	},
// 	{
// 		Code: 'PFBH',
// 		Building: 'Powell-Focht Bioengineering Hall',
// 		Location: 'Warren',
// 	},
// 	{
// 		Code: 'POTKR',
// 		Building: 'Potiker Theatre',
// 		Location: 'Revelle',
// 	},
// 	{
// 		Code: 'PRICE',
// 		Building: 'Price Center',
// 		Location: 'University Center',
// 	},
// 	{
// 		Code: 'RBC',
// 		Building: 'Robinson Building Complex',
// 		Location: 'Eleanor Roosevelt',
// 	},
// 	{
// 		Code: 'RECGM',
// 		Building: 'Recreation Gymnasium',
// 		Location: 'Muir',
// 	},
// 	{
// 		Code: 'RITTR',
// 		Building: 'Ritter Hall',
// 		Location: 'SIO',
// 	},
// 	{
// 		Code: 'RVCOM',
// 		Building: 'Revelle Commons (Plaza Caf)',
// 		Location: 'Revelle',
// 	},
// 	{ Code: 'SME', Building: 'Structural and Materials Engineering', Location: 'Sixth College' },
// 	{ Code: 'SOLIS', Building: 'Solis Lecture Hall', Location: 'Thurgood Marshall' },
// 	{ Code: 'SSB', Building: 'Social Sciences Building', Location: 'Eleanor Roosevelt' },
// 	{ Code: 'SSRB', Building: 'Chemistry Research Building', Location: 'Thurgood Marshall' },
// 	{ Code: 'SVERD', Building: 'Sverdrup Hall', Location: 'SIO' },
// 	{ Code: 'TBA', Building: 'To Be Arranged', Location: 'N/A' },
// 	{
// 		Code: 'TM101-103',
// 		Building: 'Thurgood Marshall College Trailers',
// 		Location: 'Thurgood Marshall',
// 	},
// 	{
// 		Code: 'TMCA',
// 		Building: 'Thurgood Marshall College Administration Building',
// 		Location: 'Thurgood Marshall',
// 	},
// 	{ Code: 'U201', Building: 'University Center, Building 201', Location: 'University Center' },
// 	{
// 		Code: 'U303',
// 		Building: 'University Center, Building 303, Cancer Research Facility',
// 		Location: 'University Center',
// 	},
// 	{ Code: 'U409', Building: 'University Center, Building 409', Location: 'University Center' },
// 	{ Code: 'U413', Building: 'University Center, Building 413', Location: 'Sixth' },
// 	{ Code: 'U413A', Building: 'University Center, Building 413A', Location: 'Sixth' },
// 	{ Code: 'UNEX', Building: 'UCSD Extension', Location: 'Marshall' },
// 	{ Code: 'UREY', Building: 'Urey Hall', Location: 'Revelle' },
// 	{ Code: 'URY-A', Building: 'Urey Hall Addition', Location: 'Revelle' },
// 	{ Code: 'VAF', Building: 'Visual Arts Facility', Location: 'Sixth' },
// 	{ Code: 'VAUGN', Building: 'Vaughan Hall', Location: 'SIO' },
// 	{ Code: 'WLH', Building: 'Warren Lecture Hall', Location: 'Warren' },
// 	{ Code: 'YORK', Building: 'York Hall, Undergraduate Sciences Building', Location: 'Revelle' },
// ];

export const schoolBuildings: string[] = [
	'Applied Physics and Mathematics',
	'Atkinson Hall',
	'Muir Biology Building',
	'Biomedical Library Building',
	'Biomedical Sciences Building',
	'Bonner Hall',
	'Canyon Vista Administration Building',
	'Center Hall',
	'Central Utilities Building',
	'Central Utilities Plant (CUP)',
	'Cognitive Science Building (CSB)',
	'Communication Building',
	'Computer Science and Engineering Building',
	'Continuing Education',
	'Copley International Conference Center (CICC)',
	'Crafts Center Building',
	"Dean's Residence, Assistant, Sixth College",
	'Design and Innovation Building',
	'EH&S Training Room, UCtr 401',
	'ERC Administration North',
	'ERC Administration South',
	'East Campus Office Building (ECOB)',
	'Economics Building (ECON)',
	'Eleanor Roosevelt College Administration',
	'Emeriti Association',
	'Engineering Building Unit II (EBU2)',
	'Extended Studies and Public Programs - Building A',
	'Extended Studies and Public Programs - Building B',
	'Extended Studies and Public Programs - Building C',
	'Extended Studies and Public Programs - Building D',
	'Extended Studies and Public Programs - Building E',
	'Extended Studies and Public Programs - Building F',
	'Extended Studies and Public Programs - Building G',
	'Extended Studies and Public Programs - Building H',
	'Extended Studies and Public Programs - Building J',
	'Extended Studies and Public Programs - Building K',
	'Extended Studies and Public Programs - Building M',
	'Extended Studies and Public Programs - Building N',
	'Extended Studies and Public Programs - Building O East',
	'Extended Studies and Public Programs - Building O West',
	'Extended Studies and Public Programs - Building Y',
	'Extended Studies and Public Programs - Building Z',
	'Faustina Solis Lecture Hall',
	'Fleet Services',
	'Galbraith Hall (GH)',
	'Geisel Library',
	'Gildred Latin American Studies Building',
	'Gilman Parking Structure',
	'Great Hall',
	'Guava Building',
	'Health Sciences Biomedical Research Facilities - 2',
	'Herbert F. York Undergraduate Sciences Building (USB)',
	'Holly Building',
	'Hopkins Parking Structure',
	'Humanities and Social Sciences Building (HSS)',
	'Institute of the Americas Building (IOA)',
	'Institute of the Americas Building Addition',
	'Institute on Global Conflict & Cooperation (IGCC)',
	'International Center',
	'International House',
	'Ivy Building',
	'Jacaranda Building',
	'Jacobs Hall /Engineering Building Unit I (EBU1)',
	'Laurel Building',
	'Ledden Auditorium (LEDDN)',
	'Literature Building (LIT)',
	'Magnolia Building',
	'Mandler Hall (MNDLR)',
	'Mayer Hall (MAYER)',
	'Mayer Hall Addition (MYR-A)',
	'McGill Hall (MCGIL)',
	'McGill Hall Annex (MCG-A)',
	'Medical Education and Telemedicine',
	'Medical Teaching Facility',
	'Muir Commons Annex',
	'Natural Sciences Building (NSB)',
	'Old Town Plaza',
	'Ombuds Office',
	'Original Student Center',
	'Otterson Hall (OTRSN)',
	'Pacific Hall (PACIF)',
	'Parking Security',
	'Pepper Canyon Hall (PCYNH)',
	'Peterson Hall (PETER)',
	'Powell-Focht Bioengineering Hall',
	'Preuss School - Building A',
	'Preuss School - Building B',
	'Preuss School - Building C',
	'Preuss School - Building D',
	'Preuss School - Building E',
	'Preuss School - Building F',
	'Price Center',
	'Psychology-Linguistics Building',
	'Public Health Undergraduate Student Affairs Office (U202)',
	'Revelle College Administration Building',
	'Revelle College Provost Office',
	'Robinson Administration',
	'Robinson Auditorium',
	'Robinson Building Complex (RBC)',
	'Robinson Library',
	'Sanford Consortium',
	'School of Global Policy and Strategy (GPS) - Library',
	'School of Global Policy and Strategy (GPS) - Administration',
	'School of Global Policy and Strategy (GPS) - Auditorium',
	'School of Pharmacy',
	'Science and Engineering Research Facility (SERF)',
	'Sequoyah Hall (SEQUO )',
	'Skaggs Pharmaceutical Sciences Building (PSB)',
	'Social Sciences Building (SSB)',
	'Stein Clinical Research Building',
	'Stewart Commons',
	'Structural and Materials Engineering',
	'Student Center B',
	'Student Services Center',
	'Teaching & Learning Commons',
	'Tenaya Hall (TENAY)',
	'The Black Resource Center (BRC)',
	'The Center for the Future of Surgery',
	'Third College Lecture Hall Building',
	'Thurgood Marshall Activities Center',
	'Thurgood Marshall College Administration Building',
	'Tioga Hall (TIOGA)',
	'Torrey Pines Center North',
	'Torrey Pines Center South',
	'Trailer 611 /EBU2',
	'University Center 104 (U104)',
	'University Center 105',
	'University Center 106',
	'University Center 107',
	'University Center 108 (U108)',
	'University Center 109',
	'University Center 110',
	'University Center 111',
	'University Center 112',
	'University Center 201 (U201)',
	'University Center 301 (U301)',
	'University Center 301A (U301A)',
	'University Center 302 (U302)',
	'University Center 303 (U303)',
	'University Center 400 (U400)',
	'University Center 409 (U409)',
	'University Center 413 (U413)',
	'University Center 413A (U413A)',
	'University Center 965 (U965)',
	'University Extension Complex',
	'Urey Hall (UREY)',
	'Urey Hall Addition',
	'Urey Hall Annex (URY-A)',
	'Utility Plant',
	'Visual Arts Facility (VAF)',
	'Visual Arts Facility (VIS)',
	'W.M. Keck Building (KECK)',
	'Warren Lecture Hall (WLH)',
	'Wells Fargo Hall (WFH)',
	'York Hall (YORK)',
];
