const athletes = [
	'Jim Brown',
	'Jerry Rice',
	'Joe Montana',
	'Lawrence Taylor',
	'Walter Payton',
	'Tom Brady',
	'Peyton Manning',
	'Brett Favre',
	'Barry Sanders',
	'Deion Sanders',
	'Michael Jordan',
	'LeBron James',
	'Kareem Abdul-Jabbar',
	'Magic Johnson',
	'Larry Bird',
	'Wilt Chamberlain',
	"Shaquille O'Neal",
	'Bill Russell',
	'Tim Duncan',
	'Hakeem Olajuwon',
	'Babe Ruth',
	'Jackie Robinson',
	'Willie Mays',
	'Hank Aaron',
	'Ted Williams',
	'Lou Gehrig',
	'Mickey Mantle',
	'Derek Jeter',
	'Roberto Clemente',
	'Sandy Koufax',
	'Pelé',
	'Diego Maradona',
	'Johan Cruyff',
	'Cristiano Ronaldo',
	'Lionel Messi',
	'Zinedine Zidane',
	'George Best',
	'Franz Beckenbauer',
	'Ronaldinho',
	'Thierry Henry',
	'Roger Federer',
	'Serena Williams',
	'Rod Laver',
	'Steffi Graf',
	'Bjorn Borg',
	'Martina Navratilova',
	'Pete Sampras',
	'Andre Agassi',
	'Rafael Nadal',
	'Novak Djokovic',
];

const celebrities = [
	'Leonardo DiCaprio',
	'Meryl Streep',
	'Denzel Washington',
	'Scarlett Johansson',
	'Brad Pitt',
	'Cate Blanchett',
	'Tom Hanks',
	'Natalie Portman',
	'Johnny Depp',
	'Julia Roberts',
	'Morgan Freeman',
	'Charlize Theron',
	'Robert Downey Jr.',
	'Nicole Kidman',
	'Anthony Hopkins',
	'Beyoncé',
	'Taylor Swift',
	'Ed Sheeran',
	'Adele',
	'Justin Bieber',
	'Rihanna',
	'Lady Gaga',
	'Bruno Mars',
	'Ariana Grande',
	'John Legend',
	'Katy Perry',
	'Billie Eilish',
	'Elton John',
	'Madonna',
	'Michael Jackson',
	'Steven Spielberg',
	'Quentin Tarantino',
	'Christopher Nolan',
	'Martin Scorsese',
	'Greta Gerwig',
	'Ava DuVernay',
	'Guillermo del Toro',
	'Ridley Scott',
	'Sofia Coppola',
	'Wes Anderson',
	'Karl Lagerfeld',
	'Anna Wintour',
	'Giorgio Armani',
	'Ralph Lauren',
	'Donatella Versace',
	'Stella McCartney',
	'Marc Jacobs',
	'Tom Ford',
	'Christian Louboutin',
	'Diane von Fürstenberg',
	'J.K. Rowling',
	'Stephen King',
	'George R.R. Martin',
	'Chimamanda Ngozi Adichie',
	'Haruki Murakami',
	'Margaret Atwood',
	'Dan Brown',
	'Jodi Picoult',
	'Paulo Coelho',
	'Neil Gaiman',
	'Ellen DeGeneres',
	'Jerry Seinfeld',
	'Ricky Gervais',
	'Amy Schumer',
	'Dave Chappelle',
	'Tina Fey',
	'Kevin Hart',
	"Conan O'Brien",
	'Sarah Silverman',
	'Chris Rock',
	'Oprah Winfrey',
	'Jimmy Fallon',
	'Jimmy Kimmel',
	'Stephen Colbert',
	'Trevor Noah',
	'David Letterman',
	'Anderson Cooper',
	'Ryan Seacrest',
	"Conan O'Brien",
	'Barack Obama',
	'Angela Merkel',
	'Vladimir Putin',
	'Justin Trudeau',
	'Emmanuel Macron',
	'Michelle Obama',
	'Jacinda Ardern',
	'Boris Johnson',
	'Kamala Harris',
	'Joe Biden',
	'Elon Musk',
	'Jeff Bezos',
	'Mark Zuckerberg',
	'Tim Cook',
	'Bill Gates',
	'Jack Dorsey',
	'Larry Page',
	'Sergey Brin',
	'Richard Branson',
	'Oprah Winfrey',
];

export const randomNames = athletes.concat(celebrities);
